Substitute OpenBeans for java.beans so Android tests work
The Android implementation of java.beans does not include everything
which gives rise to error messages like this:

    E/TestRunner: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/beans/Introspector; at
       org.powermock.configuration.support.ConfigurationMapper.map(ConfigurationMapper.java:44) at
       org.powermock.configuration.support.ConfigurationBuilder$ConfigurationCreator.mapConfiguration(ConfigurationBuilder.java:80) at
       ...

While it's not clear to me why such abject fanciness is needed in the
ConfigurationMapper to take care of a sum total of three properties,
it is clear that this change represents a minimum of source changes to
get to a working state.

Fixes #1062